name: MEAN-Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@v1.2.0

        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

          script: |
            cd /home/karan/kizaFrontend/
            git pull origin main
            sudo npm i
            sudo npm i pm2 -g
            npm run build
            cd /home/karan/kizaFrontend/dist/front-end
            sudo npm i http-server -g
            pm2 start --name "test" http-server -- -p 4200 -d false
